version: 2

updates:
  - package-ecosystem: 'npm'
    directory: 'backend'
    schedule:
      interval: 'weekly'
    groups:
      backend-updates:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: 'frontend'
    schedule:
      interval: 'weekly'
    groups:
      angular:
        patterns:
          - '@angular*'
      non-angular:
        patterns:
          - '*'
        exclude-patterns:
          - '@angular*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      actions:
        patterns:
          - '*'
